baseURL = "https://elastic-pare-a76afb.netlify.app/"
languageCode = "en-us"


theme = ["hugo-clarity"]
title = "My testing site"

[params]
author = "Rudi Martinsen"
description = "Testing Testing Testing"

